name: Publish ResponseApi to nuget
on:
  push:
    branches:
    - main
env:
  PROJECT_PATH: 'src/ResponseApi/ResponseApi.csproj'
jobs:
  build-test-publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        # Restore
      - name: Install dependencies
        run: dotnet restore
        # Build
      - name: Build
        run: dotnet build --configuration Release --no-restore
        # Tests
      - name: Test
        run: dotnet test     
# Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{env.PROJECT_PATH}} # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
